version: '3'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/config.hcl:/vault/config.hcl
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config.hcl

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports: 
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
volumes:
  vault-data:
